export const data = {
  responseCode: '1',
  msg: 'SUCCESS',
  content: {
    id: 7,
    displayId: 'HE7',
    handlerFullName: 'Johanson Jack',
    handlerNickname: 'Jackson',
    reporterFullName: null,
    reporterNickname: null,
    title1: 'Completed',
    title2: 'Case has been completed on',
    title3: '2022-04-01',
    title4: '15:49:17',
    logo: 'done',
    titleBackground: '#409D2F',
    status: 'Completed',
    caseDetailsSubList: [
      {
        title: 'Completed',
        body1: 'Case has been completed.',
        body2: 'by:',
        nickname: 'admin 001',
        fullName: 'Admin001',
        date: '2022-04-01',
        time: '15:49:17',
        hasProof: true,
        panicAlertInfo: [
          {
            infoType: 'IMAGE',
            value:
              'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
            type: null,
            createdDatetime: '2022-04-01 15:49:17',
          },
          {
            infoType: 'IMAGE',
            value:
              'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
            type: null,
            createdDatetime: '2022-04-01 15:49:17',
          },
          {
            infoType: 'IMAGE',
            value:
              'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
            type: null,
            createdDatetime: '2022-04-01 15:49:17',
          },
        ],
        proofList: [
          'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
          'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
          'https://images.pexels.com/photos/5404028/pexels-photo-5404028.jpeg',
        ],
        proofTypeList: ['IMAGE', 'IMAGE', 'IMAGE'],
        remarks: '3242423423',
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Processing',
        body1: 'Case has been accepted and handled by ',
        body2: '',
        nickname: 'admin 001',
        fullName: 'ADMIN001',
        date: '2021-11-24',
        time: '13:24:27',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
      {
        title: 'Submitted',
        body1: 'New case submitted',
        body2: 'by:',
        nickname: 'Jack',
        fullName: 'Doctor Stranger',
        date: '2021-11-24',
        time: '11:35:49',
        hasProof: false,
        panicAlertInfo: [],
        proofList: [],
        proofTypeList: [],
        remarks: null,
      },
    ],
  },
  content2: null,
  content3: null,
  totalPage: 0,
};
